export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-emerald-950 via-black to-black text-white px-6 py-12">
      <div className="mx-auto max-w-3xl rounded-3xl border border-yellow-400/30 bg-black/40 p-6 md:p-10 shadow-[0_0_45px_rgba(250,204,21,0.15)]">
        <h1 className="text-3xl md:text-4xl font-bold text-yellow-300">
          Entertainment Disclaimer
        </h1>

        <p className="mt-4 text-white/70">Last updated: June 2026</p>

        <section className="mt-8 space-y-5 text-white/80 leading-relaxed">
          <p>
            THE CHARIOT / TAROT PREMIUM is a digital tarot-style reading service
            created for entertainment, reflection, and personal insight.
          </p>

          <h2 className="text-xl font-semibold text-yellow-200">
            1. Entertainment Purpose Only
          </h2>
          <p>
            The readings generated by this service are for entertainment and
            self-reflection only. They should not be treated as absolute truth,
            prediction, guarantee, or professional advice.
          </p>

          <h2 className="text-xl font-semibold text-yellow-200">
            2. No Medical, Legal, or Financial Advice
          </h2>
          <p>
            This service does not provide medical, legal, financial,
            psychological, or professional advice. For serious matters, users
            should consult qualified professionals.
          </p>

          <h2 className="text-xl font-semibold text-yellow-200">
            3. User Responsibility
          </h2>
          <p>
            Users are fully responsible for their own decisions. THE CHARIOT /
            TAROT PREMIUM is not responsible for actions taken based on a
            reading.
          </p>

          <h2 className="text-xl font-semibold text-yellow-200">
            4. AI-Generated Content
          </h2>
          <p>
            Some readings may be generated with the assistance of artificial
            intelligence. The content may not always be accurate, complete, or
            suitable for every situation.
          </p>

          <h2 className="text-xl font-semibold text-yellow-200">
            5. Payment and Access
          </h2>
          <p>
            Premium payment only provides access to digital entertainment
            features. It does not guarantee any specific personal outcome,
            prediction, or result.
          </p>
        </section>
      </div>
    </main>
  );
}